openapi: 3.0.0
info:
  version: 0.9.6
  title: Swarm Debug API
  description: 'A list of the currently provided debug interfaces to interact with the swarm node'
security:
  - {}
externalDocs:
  description: Browse the documentations @ Swarm-guide
  url: 'https://swarm-guide.readthedocs.io/en/latest/'
servers:
  - url: '{apiRoot}'
    variables:
      apiRoot:
        default: http://localhost:6061/
        description: Base address of the local Swarm node debug API
paths:
  '/addresses':
    get:
      summary: 'Get addresses'
      tags: 
        - 'Swarm Debug Endpoints'
      responses:
        default:
          description: Default response

  '/connect/{multi-address:.+}':
    post:
      summary: 'Connect to address'
      tags: 
        - 'Swarm Debug Endpoints'
      responses:
        default:
          description: Default response

  '/peers':
    get:
      summary: 'Get a list of peers'
      tags: 
        - 'Swarm Debug Endpoints'
      responses:
        default:
          description: Default response

  '/peers/{address}':
    delete:
      summary: 'Remove peer'
      tags: 
        - 'Swarm Debug Endpoints'
      responses:
        default:
          description: Default response

  '/chunks/{address}':
    get:
      summary: 'Get chunk address'
      tags: 
        - 'Swarm Debug Endpoints'
      responses:
        default:
          description: Default response

  '/chunks-pin/{address}':
    post:
      summary: 'Pin chunk with given address'
      tags: 
        - 'Swarm Debug Endpoints'
      responses:
        default:
          description: Default response
    delete:
      summary: 'Unpin chunk with given address'
      tags: 
        - 'Swarm Debug Endpoints'
      responses:
        default:
          description: Default response
    get:
      summary: 'Get pinning status of chunk with given address'
      tags: 
        - 'Swarm Debug Endpoints'
      responses:
        default:
          description: Default response

  '/chunks-pin/':
    get:
      summary: 'Get list of pinned chunks'
      tags: 
        - 'Swarm Debug Endpoints'
      responses:
        default:
          description: Default response      

  '/topology':
    get:
      summary: 'Get topology'
      tags: 
        - 'Swarm Debug Endpoints'
      responses:
        default:
          description: Default response      
